<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Character;

class CharacterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $charactersRecords = [
            [
                "id" => "1001",
                "name" => "March 7th",
                "tag" => "march-7th",
                "rarity" => 4,
                "path_id" => 6,
                "element" => "Ice",
                "max_sp" => 120,
                "release_version" => "1.0",
                "icon" => "icon/character/1001.png",
                "preview" => "image/character_preview/1001.png",
                "portrait" => "image/character_portrait/1001.png"
            ],
            [
                "id" => "1002",
                "name" => "Dan Heng",
                "tag" => "dan-heng",
                "rarity" => 4,
                "path_id" => 2,
                "element" => "Wind",
                "max_sp" => 100,
                "release_version" => "1.0",
                "icon" => "icon/character/1002.png",
                "preview" => "image/character_preview/1002.png",
                "portrait" => "image/character_portrait/1002.png"
            ],
            [
                "id" => "1003",
                "name" => "Himeko",
                "tag" => "himeko",
                "rarity" => 5,
                "path_id" => 3,
                "element" => "Fire",
                "max_sp" => 120,
                "release_version" => "1.0",
                "icon" => "icon/character/1003.png",
                "preview" => "image/character_preview/1003.png",
                "portrait" => "image/character_portrait/1003.png"
            ],
            [
                "id" => "1004",
                "name" => "Welt",
                "tag" => "welt",
                "rarity" => 5,
                "path_id" => 5,
                "element" => "Imaginary",
                "max_sp" => 120,
                "release_version" => "1.0",
                "icon" => "icon/character/1004.png",
                "preview" => "image/character_preview/1004.png",
                "portrait" => "image/character_portrait/1004.png"
            ],
            [
                "id" => "1005",
                "name" => "Kafka",
                "tag" => "kafka",
                "rarity" => 5,
                "path_id" => 5,
                "element" => "Thunder",
                "max_sp" => 120,
                "release_version" => "1.2",
                "icon" => "icon/character/1005.png",
                "preview" => "image/character_preview/1005.png",
                "portrait" => "image/character_portrait/1005.png"
            ],
            [
                "id" => "1006",
                "name" => "Silver Wolf",
                "tag" => "silver-wolf",
                "rarity" => 5,
                "path_id" => 5,
                "element" => "Quantum",
                "max_sp" => 110,
                "release_version" => "1.1",
                "icon" => "icon/character/1006.png",
                "preview" => "image/character_preview/1006.png",
                "portrait" => "image/character_portrait/1006.png"
            ],
            [
                "id" => "1008",
                "name" => "Arlan",
                "tag" => "arlan",
                "rarity" => 4,
                "path_id" => 1,
                "element" => "Thunder",
                "max_sp" => 110,
                "release_version" => "1.0",
                "icon" => "icon/character/1008.png",
                "preview" => "image/character_preview/1008.png",
                "portrait" => "image/character_portrait/1008.png"
            ],
            [
                "id" => "1009",
                "name" => "Asta",
                "tag" => "asta",
                "rarity" => 4,
                "path_id" => 4,
                "element" => "Fire",
                "max_sp" => 120,
                "release_version" => "1.0",
                "icon" => "icon/character/1009.png",
                "preview" => "image/character_preview/1009.png",
                "portrait" => "image/character_portrait/1009.png"
            ],
            [
                "id" => "1013",
                "name" => "Herta",
                "tag" => "herta",
                "rarity" => 4,
                "path_id" => 3,
                "element" => "Ice",
                "max_sp" => 110,
                "release_version" => "1.0",
                "icon" => "icon/character/1013.png",
                "preview" => "image/character_preview/1013.png",
                "portrait" => "image/character_portrait/1013.png"
            ],
            [
                "id" => "1101",
                "name" => "Bronya",
                "tag" => "bronya",
                "rarity" => 5,
                "path_id" => 4,
                "element" => "Wind",
                "max_sp" => 120,
                "release_version" => "1.0",
                "icon" => "icon/character/1101.png",
                "preview" => "image/character_preview/1101.png",
                "portrait" => "image/character_portrait/1101.png"
            ],
            [
                "id" => "1102",
                "name" => "Seele",
                "tag" => "seele",
                "rarity" => 5,
                "path_id" => 2,
                "element" => "Quantum",
                "max_sp" => 120,
                "release_version" => "1.0",
                "icon" => "icon/character/1102.png",
                "preview" => "image/character_preview/1102.png",
                "portrait" => "image/character_portrait/1102.png"
            ],
            [
                "id" => "1103",
                "name" => "Serval",
                "tag" => "serval",
                "rarity" => 4,
                "path_id" => 3,
                "element" => "Thunder",
                "max_sp" => 100,
                "release_version" => "1.0",
                "icon" => "icon/character/1103.png",
                "preview" => "image/character_preview/1103.png",
                "portrait" => "image/character_portrait/1103.png"
            ],
            [
                "id" => "1104",
                "name" => "Gepard",
                "tag" => "gepard",
                "rarity" => 5,
                "path_id" => 6,
                "element" => "Ice",
                "max_sp" => 100,
                "release_version" => "1.0",
                "icon" => "icon/character/1104.png",
                "preview" => "image/character_preview/1104.png",
                "portrait" => "image/character_portrait/1104.png"
            ],
            [
                "id" => "1105",
                "name" => "Natasha",
                "tag" => "natasha",
                "rarity" => 4,
                "path_id" => 7,
                "element" => "Physical",
                "max_sp" => 90,
                "release_version" => "1.0",
                "icon" => "icon/character/1105.png",
                "preview" => "image/character_preview/1105.png",
                "portrait" => "image/character_portrait/1105.png"
            ],
            [
                "id" => "1106",
                "name" => "Pela",
                "tag" => "pela",
                "rarity" => 4,
                "path_id" => 5,
                "element" => "Ice",
                "max_sp" => 110,
                "release_version" => "1.0",
                "icon" => "icon/character/1106.png",
                "preview" => "image/character_preview/1106.png",
                "portrait" => "image/character_portrait/1106.png"
            ],
            [
                "id" => "1107",
                "name" => "Clara",
                "tag" => "clara",
                "rarity" => 5,
                "path_id" => 1,
                "element" => "Physical",
                "max_sp" => 110,
                "release_version" => "1.0",
                "icon" => "icon/character/1107.png",
                "preview" => "image/character_preview/1107.png",
                "portrait" => "image/character_portrait/1107.png"
            ],
            [
                "id" => "1108",
                "name" => "Sampo",
                "tag" => "sampo",
                "rarity" => 4,
                "path_id" => 5,
                "element" => "Wind",
                "max_sp" => 120,
                "release_version" => "1.0",
                "icon" => "icon/character/1108.png",
                "preview" => "image/character_preview/1108.png",
                "portrait" => "image/character_portrait/1108.png"
            ],
            [
                "id" => "1109",
                "name" => "Hook",
                "tag" => "hook",
                "rarity" => 4,
                "path_id" => 1,
                "element" => "Fire",
                "max_sp" => 120,
                "release_version" => "1.0",
                "icon" => "icon/character/1109.png",
                "preview" => "image/character_preview/1109.png",
                "portrait" => "image/character_portrait/1109.png"
            ],
            [
                "id" => "1110",
                "name" => "Lynx",
                "tag" => "lynx",
                "rarity" => 4,
                "path_id" => 7,
                "element" => "Quantum",
                "max_sp" => 100,
                "release_version" => "1.3",
                "icon" => "icon/character/1110.png",
                "preview" => "image/character_preview/1110.png",
                "portrait" => "image/character_portrait/1110.png"
            ],
            [
                "id" => "1111",
                "name" => "Luka",
                "tag" => "luka",
                "rarity" => 4,
                "path_id" => 5,
                "element" => "Physical",
                "max_sp" => 130,
                "release_version" => "1.2",
                "icon" => "icon/character/1111.png",
                "preview" => "image/character_preview/1111.png",
                "portrait" => "image/character_portrait/1111.png"
            ],
            [
                "id" => "1112",
                "name" => "Topaz",
                "tag" => "topaz",
                "rarity" => 5,
                "path_id" => 2,
                "element" => "Fire",
                "max_sp" => 130,
                "release_version" => "1.4",
                "icon" => "icon/character/1112.png",
                "preview" => "image/character_preview/1112.png",
                "portrait" => "image/character_portrait/1112.png"
            ],
            [
                "id" => "1201",
                "name" => "Qingque",
                "tag" => "qingque",
                "rarity" => 4,
                "path_id" => 3,
                "element" => "Quantum",
                "max_sp" => 140,
                "release_version" => "1.0",
                "icon" => "icon/character/1201.png",
                "preview" => "image/character_preview/1201.png",
                "portrait" => "image/character_portrait/1201.png"
            ],
            [
                "id" => "1202",
                "name" => "Tingyun",
                "tag" => "tingyun",
                "rarity" => 4,
                "path_id" => 4,
                "element" => "Thunder",
                "max_sp" => 130,
                "release_version" => "1.0",
                "icon" => "icon/character/1202.png",
                "preview" => "image/character_preview/1202.png",
                "portrait" => "image/character_portrait/1202.png"
            ],
            [
                "id" => "1203",
                "name" => "Luocha",
                "tag" => "luocha",
                "rarity" => 5,
                "path_id" => 7,
                "element" => "Imaginary",
                "max_sp" => 100,
                "release_version" => "1.1",
                "icon" => "icon/character/1203.png",
                "preview" => "image/character_preview/1203.png",
                "portrait" => "image/character_portrait/1203.png"
            ],
            [
                "id" => "1204",
                "name" => "Jing Yuan",
                "tag" => "jing-yuan",
                "rarity" => 5,
                "path_id" => 3,
                "element" => "Thunder",
                "max_sp" => 130,
                "release_version" => "1.0",
                "icon" => "icon/character/1204.png",
                "preview" => "image/character_preview/1204.png",
                "portrait" => "image/character_portrait/1204.png"
            ],
            [
                "id" => "1205",
                "name" => "Blade",
                "tag" => "blade",
                "rarity" => 5,
                "path_id" => 1,
                "element" => "Wind",
                "max_sp" => 130,
                "release_version" => "1.2",
                "icon" => "icon/character/1205.png",
                "preview" => "image/character_preview/1205.png",
                "portrait" => "image/character_portrait/1205.png"
            ],
            [
                "id" => "1206",
                "name" => "Sushang",
                "tag" => "sushang",
                "rarity" => 4,
                "path_id" => 2,
                "element" => "Physical",
                "max_sp" => 120,
                "release_version" => "1.0",
                "icon" => "icon/character/1206.png",
                "preview" => "image/character_preview/1206.png",
                "portrait" => "image/character_portrait/1206.png"
            ],
            [
                "id" => "1207",
                "name" => "Yukong",
                "tag" => "yukong",
                "rarity" => 4,
                "path_id" => 4,
                "element" => "Imaginary",
                "max_sp" => 130,
                "release_version" => "1.1",
                "icon" => "icon/character/1207.png",
                "preview" => "image/character_preview/1207.png",
                "portrait" => "image/character_portrait/1207.png"
            ],
            [
                "id" => "1208",
                "name" => "Fu Xuan",
                "tag" => "fuxuan",
                "rarity" => 5,
                "path_id" => 6,
                "element" => "Quantum",
                "max_sp" => 135,
                "release_version" => "1.3",
                "icon" => "icon/character/1208.png",
                "preview" => "image/character_preview/1208.png",
                "portrait" => "image/character_portrait/1208.png"
            ],
            [
                "id" => "1209",
                "name" => "Yanqing",
                "tag" => "yanqing",
                "rarity" => 5,
                "path_id" => 2,
                "element" => "Ice",
                "max_sp" => 140,
                "release_version" => "1.0",
                "icon" => "icon/character/1209.png",
                "preview" => "image/character_preview/1209.png",
                "portrait" => "image/character_portrait/1209.png"
            ],
            [
                "id" => "1210",
                "name" => "Guinaifen",
                "tag" => "guinaifen",
                "rarity" => 4,
                "path_id" => 5,
                "element" => "Fire",
                "max_sp" => 120,
                "release_version" => "1.4",
                "icon" => "icon/character/1210.png",
                "preview" => "image/character_preview/1210.png",
                "portrait" => "image/character_portrait/1210.png"
            ],
            [
                "id" => "1211",
                "name" => "Bailu",
                "tag" => "bailu",
                "rarity" => 5,
                "path_id" => 7,
                "element" => "Thunder",
                "max_sp" => 100,
                "release_version" => "1.0",
                "icon" => "icon/character/1211.png",
                "preview" => "image/character_preview/1211.png",
                "portrait" => "image/character_portrait/1211.png"
            ],
            [
                "id" => "1212",
                "name" => "Jingliu",
                "tag" => "jingliu",
                "rarity" => 5,
                "path_id" => 1,
                "element" => "Ice",
                "max_sp" => 140,
                "release_version" => "1.4",
                "icon" => "icon/character/1212.png",
                "preview" => "image/character_preview/1212.png",
                "portrait" => "image/character_portrait/1212.png"
            ],
            [
                "id" => "1213",
                "name" => "Dan Heng IL",
                "tag" => "dan-heng-il",
                "rarity" => 5,
                "path_id" => 1,
                "element" => "Imaginary",
                "max_sp" => 140,
                "release_version" => "1.3",
                "icon" => "icon/character/1213.png",
                "preview" => "image/character_preview/1213.png",
                "portrait" => "image/character_portrait/1213.png"
            ],
            [
                "id" => "1214",
                "name" => "Xueyi",
                "tag" => "xueyi",
                "rarity" => 4,
                "path_id" => 1,
                "element" => "Quantum",
                "max_sp" => 120,
                "release_version" => "1.6",
                "icon" => "icon/character/1214.png",
                "preview" => "image/character_preview/1214.png",
                "portrait" => "image/character_portrait/1214.png"
            ],
            [
                "id" => "1215",
                "name" => "Hanya",
                "tag" => "hanya",
                "rarity" => 4,
                "path_id" => 4,
                "element" => "Physical",
                "max_sp" => 140,
                "release_version" => "1.5",
                "icon" => "icon/character/1215.png",
                "preview" => "image/character_preview/1215.png",
                "portrait" => "image/character_portrait/1215.png"
            ],
            [
                "id" => "1217",
                "name" => "Huohuo",
                "tag" => "huohuo",
                "rarity" => 5,
                "path_id" => 7,
                "element" => "Wind",
                "max_sp" => 140,
                "release_version" => "1.5",
                "icon" => "icon/character/1217.png",
                "preview" => "image/character_preview/1217.png",
                "portrait" => "image/character_portrait/1217.png"
            ],
            [
                "id" => "1302",
                "name" => "Argenti",
                "tag" => "argenti",
                "rarity" => 5,
                "path_id" => 3,
                "element" => "Physical",
                "max_sp" => 180,
                "release_version" => "1.5",
                "icon" => "icon/character/1302.png",
                "preview" => "image/character_preview/1302.png",
                "portrait" => "image/character_portrait/1302.png"
            ],
            [
                "id" => "1303",
                "name" => "Ruan Mei",
                "tag" => "ruan-mei",
                "rarity" => 5,
                "path_id" => 4,
                "element" => "Ice",
                "max_sp" => 130,
                "release_version" => "1.6",
                "icon" => "icon/character/1303.png",
                "preview" => "image/character_preview/1303.png",
                "portrait" => "image/character_portrait/1303.png"
            ],
            [
                "id" => "1305",
                "name" => "Dr. Ratio",
                "tag" => "dr-ratio",
                "rarity" => 5,
                "path_id" => 2,
                "element" => "Imaginary",
                "max_sp" => 140,
                "release_version" => "1.6",
                "icon" => "icon/character/1305.png",
                "preview" => "image/character_preview/1305.png",
                "portrait" => "image/character_portrait/1305.png"
            ],
            [
                "id" => "1306",
                "name" => "Sparkle",
                "tag" => "sparkle",
                "rarity" => 5,
                "path_id" => 4,
                "element" => "Quantum",
                "max_sp" => 110,
                "release_version" => "2.0",
                "icon" => "icon/character/1306.png",
                "preview" => "image/character_preview/1306.png",
                "portrait" => "image/character_portrait/1306.png"
            ],
            [
                "id" => "1307",
                "name" => "Black Swan",
                "tag" => "black-swan",
                "rarity" => 5,
                "path_id" => 5,
                "element" => "Wind",
                "max_sp" => 120,
                "release_version" => "2.0",
                "icon" => "icon/character/1307.png",
                "preview" => "image/character_preview/1307.png",
                "portrait" => "image/character_portrait/1307.png"
            ],
            [
                "id" => "1312",
                "name" => "Misha",
                "tag" => "misha",
                "rarity" => 4,
                "path_id" => 1,
                "element" => "Ice",
                "max_sp" => 100,
                "release_version" => "2.0",
                "icon" => "icon/character/1312.png",
                "preview" => "image/character_preview/1312.png",
                "portrait" => "image/character_portrait/1312.png"
            ],
            [
                "id" => "8001",
                "name" => "Trailblazer (Physical)",
                "tag" => "trailblazer-physical",
                "rarity" => 5,
                "path_id" => 1,
                "element" => "Physical",
                "max_sp" => 120,
                "release_version" => "1.0",
                "icon" => "icon/character/8001.png",
                "preview" => "image/character_preview/8001.png",
                "portrait" => "image/character_portrait/8001.png"
            ],
            [
                "id" => "8003",
                "name" => "Trailblazer (Fire)",
                "tag" => "trailblazer-fire",
                "rarity" => 5,
                "path_id" => 6,
                "element" => "Fire",
                "max_sp" => 120,
                "release_version" => "1.0",
                "icon" => "icon/character/8003.png",
                "preview" => "image/character_preview/8003.png",
                "portrait" => "image/character_portrait/8003.png"
            ]
        ];

        Character::insert($charactersRecords);
    }
}
